service: demo-lambda
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  # todo: set minimal access
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "rds:*"
       - "ssm:*"
       - "secretsmanager:*"
       - "kms:Decrypt"
       - "ec2:*"
     Resource: "*"
  vpc:
    securityGroupIds:
      - ${ssm:/database/demo_db/lambda_sg}
    subnetIds:
      Fn::Split:
        - ","
        - ${ssm:/database/demo_db/subnet_ids}
  environment:
    DATABASE_ENDPOINT: ${ssm:/database/demo_db/endpoint~true}
    DATABASE_NAME: ${ssm:/database/demo_db/name~true}
    DATABASE_USER: ${ssm:/database/demo_db/user~true}
    DATABASE_PASSWORD: ${ssm:/database/demo_db/password~true}

functions:
  insert:
    handler: handler.insert
  get_things:
    handler: handler.get_things